project_id = "skadrakhzwdmxlmbgent"

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.get-vapid-key]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = true

[functions.send-scheduled-notifications]
verify_jwt = false
